### ISSUE TITLE
Remove text from our team>support

### ISSUE THREAD

**Issue by andrewtpham** [open-build/eLearning#6]
Under "Support" section, there is extra text about locations that can be removed. The text to remove is "In order to provide support for our projects around the world, our distributed team is currently based in 3 locations: Portland, USA; Berlin, Germany; Nairobi, Kenya; and soon in, Ho Chi Minh City, Vietnam."

**Comment by mesini** [comment]
Actually I though the text is removed.

**Comment by odenypeter** [comment]
Yes @mesini .The text was alreays removed. Catching up with production release.
